spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/paste_code?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: paste_code
    password: pc12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 24517